server:
  port: 8477
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#      routes:
#        - id: SERVICE-A
#          uri: lb://SERVICE-A
#          predicates:
#            - Path=/SERVICE-A/**
#        - id: SERVICE-MING
#          uri: lb://SERVICE-MING
#          predicates:
#            - Path=/SERVICE-MING/**
    nacos:
      discovery:
        server-addr: 10.211.55.101:8848
logging:
  level:
    org.springframework.cloud.gateway: debug

#spring.cloud.gateway.discovery.locator.enabled=true
#请求路径上的服务名配置为小写.比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.org.springframework.cloud.gateway=DEBUG